remote_theme: mikearnaldi/just-the-docs
search_enabled: true
aux_links:
  "Docs":
    - "//effect-ts.github.io/experimental"
  "API Reference":
    - "//effect-ts.github.io/experimental/docs/modules"
  "GitHub":
    - "//github.com/effect-ts/experimental"
